/**
 * Long-form evergreen guides — US nutrition data, USDA methodology, and label reading.
 * Hub pages that link deep into the food × nutrient matrix.
 * Each guide targets a high-intent health-conscious consumer question.
 */

export interface Guide {
  slug: string;
  title: string;
  description: string;
  intro: string;
  sections: Array<{ heading: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  category: string;
  updatedAt: string;
}

const u = '2026-04-10';

export const guides: Guide[] = [
  {
    slug: 'usda-fooddata-central',
    title: 'USDA FoodData Central: How the Government Tracks Every Nutrient',
    description: 'How the USDA maintains the most comprehensive food composition database in the world, the difference between SR Legacy, FNDDS, and branded databases, and how to use FoodData Central for accurate nutrition data.',
    category: 'Data Sources',
    updatedAt: u,
    intro: `<p>Every nutrition label, calorie counter app, and dietary recommendation in the United States traces back to a single source: the USDA's food composition databases, now consolidated into FoodData Central. This system tracks up to 150 nutrients for tens of thousands of foods, from raw ingredients to branded products. Yet most consumers (and even many nutritionists) don't know how the data is collected, what its limitations are, or how to access the most accurate version. This guide explains the system, the different database types, and how to use FoodData Central for lookup that's more accurate than any consumer app.</p>`,
    sections: [
      {
        heading: 'What FoodData Central is',
        html: `<p>FoodData Central (fdc.nal.usda.gov) is the USDA's integrated food composition database system, launched in 2019 to consolidate several previously separate databases. It contains nutritional data for over 300,000 food entries from multiple data types:</p><ul><li><strong>SR Legacy (Standard Reference):</strong> the foundational dataset with ~7,800 foods and up to 150 nutrients per food. Based on laboratory analysis. The gold standard for raw ingredients and generic foods.</li><li><strong>FNDDS (Food and Nutrient Database for Dietary Studies):</strong> ~7,000 foods typically consumed in the US, with portion size data. Used in national nutrition surveys (NHANES).</li><li><strong>Foundation Foods:</strong> a newer, more detailed dataset with extensive metadata on analytical methods, sampling procedures, and nutrient variability.</li><li><strong>Branded Foods (GDSN):</strong> ~400,000+ branded product entries from manufacturers' label data. The most specific for packaged foods but relies on manufacturer-reported data.</li><li><strong>Experimental Foods:</strong> research-grade data from specific USDA studies.</li></ul><p>For most consumer lookups, SR Legacy gives the most accurate data for whole/raw foods, and Branded Foods gives the most accurate for packaged products. FNDDS is best for mixed dishes and recipes as typically consumed.</p>`,
      },
      {
        heading: 'How the data is collected',
        html: `<p>SR Legacy and Foundation Foods are based on actual laboratory analysis:</p><ol><li><strong>Food sampling:</strong> USDA purchases representative samples of each food from multiple US regions and retail outlets. For fruits and vegetables, samples span multiple growing seasons and varieties.</li><li><strong>Laboratory analysis:</strong> samples are analyzed using standardized chemical methods (AOAC International methods) for macronutrients (protein, fat, carbohydrate, fiber), minerals, vitamins, amino acids, fatty acids, and other components.</li><li><strong>Compositing:</strong> results from multiple samples are combined into a single "mean" value with measures of variability. The value you see for "banana, raw" in USDA data is the average of many bananas from many sources.</li><li><strong>Review and publication:</strong> data undergoes quality checks and is published with source documentation.</li></ol><p>Branded Foods data comes from a different process: manufacturers submit label data to the Global Data Synchronization Network (GDSN), which USDA imports. This data reflects what's on the Nutrition Facts label — it's manufacturer-reported, not independently verified by USDA lab analysis.</p><p>The practical difference: SR Legacy data for "cheddar cheese" is based on laboratory analysis of multiple cheese samples. Branded data for "Kraft Natural Medium Cheddar Cheese" is what Kraft reported on the label. Label data has legal accuracy requirements (±20% of stated values per FDA) but is not independently verified for every product.</p>`,
      },
      {
        heading: 'The ±20% label accuracy rule',
        html: `<p>FDA regulations require that the nutrient values on Nutrition Facts labels be accurate within specific margins:</p><ul><li><strong>Calories:</strong> must be within ±20% of the stated value</li><li><strong>Total fat, saturated fat, cholesterol, sodium, total carbohydrate, dietary fiber, sugars, protein:</strong> must be within ±20%</li><li><strong>Vitamins and minerals:</strong> must contain at least 80% of the stated amount (can contain more)</li></ul><p>This means a food labeled at 200 calories could legally contain anywhere from 160 to 240 calories. For someone tracking calories carefully, this ±20% tolerance is significant — a daily intake of 2,000 calories could actually be anywhere from 1,600 to 2,400 calories based on label accuracy alone.</p><p>Research on actual label accuracy:</p><ul><li>Urban et al. (2010): analyzed 24 restaurant and frozen food items, found calorie content averaged 8% above label values, with some items exceeding label by 25-50%.</li><li>Jumpertz et al. (2013): found systematic under-reporting of calories in processed foods.</li><li>Generally: labels tend to UNDERSTATE rather than overstate calories. Foods marketed as "low calorie" or "diet" are more likely to exceed label values.</li></ul><p>For accurate tracking, use USDA SR Legacy data for whole foods (laboratory-verified) and treat branded label data as approximate.</p>`,
      },
      {
        heading: 'How to use FoodData Central',
        html: `<p>Three ways to access FoodData Central data:</p><ol><li><strong>Web search (fdc.nal.usda.gov):</strong> free, searchable database. Enter a food name, browse results, filter by data type (SR Legacy, Branded, FNDDS). Each result shows full nutrient profile per 100g and per common portion.</li><li><strong>API access (api.nal.usda.gov):</strong> free API key for developers. Programmatic access to the full database. Used by most nutrition apps (MyFitnessPal, Cronometer, etc.) as their underlying data source.</li><li><strong>Downloadable datasets:</strong> full database downloads in CSV and JSON formats for research and analysis. Available at fdc.nal.usda.gov/download-datasets.html.</li></ol><p>Search tips:</p><ul><li><strong>For whole foods:</strong> search by common name ("chicken breast, raw") and filter by SR Legacy or Foundation Foods for the most accurate data</li><li><strong>For branded products:</strong> search by brand and product name, filter by Branded Foods</li><li><strong>For mixed dishes:</strong> search FNDDS ("chicken stir fry") for typical American mixed dish compositions</li><li><strong>Use NDB number:</strong> each food has a unique NDB number. Once you find the right entry, bookmark the NDB number for future reference.</li></ul>`,
      },
      {
        heading: 'Why app data differs from USDA',
        html: `<p>Calorie counting apps (MyFitnessPal, Lose It!, Cronometer) use USDA data as a foundation but supplement it with user-submitted data and branded product databases. This creates accuracy issues:</p><ul><li><strong>User-submitted entries:</strong> anyone can add a food to MyFitnessPal. User entries are not verified and frequently contain errors (wrong serving sizes, missing nutrients, duplicates with different values).</li><li><strong>Outdated entries:</strong> food products change formulations. A MyFitnessPal entry from 2018 may not match the current product.</li><li><strong>Portion size confusion:</strong> "1 cup" of rice can mean raw or cooked (raw is ~700 calories, cooked ~200 calories). Apps don't always clarify.</li><li><strong>Restaurant items:</strong> often estimated rather than measured. Portion sizes at restaurants are not standardized.</li></ul><p>For the most accurate tracking:</p><ul><li>Use USDA FoodData Central directly for whole food lookups</li><li>Use Cronometer (which uses USDA data with less user contamination) over MyFitnessPal for accuracy</li><li>Weigh food with a kitchen scale rather than using cup/tablespoon measures (weight is more accurate than volume for solid foods)</li><li>Cross-check branded product entries against the actual Nutrition Facts label on the package</li></ul>`,
      },
      {
        heading: 'The nutrients USDA tracks (and the ones it doesn\'t)',
        html: `<p>SR Legacy tracks up to 150 nutrients per food, including:</p><ul><li><strong>Macronutrients:</strong> protein, total fat, carbohydrate, fiber, sugars, water, ash</li><li><strong>Energy:</strong> calories (from Atwater factors and specific calorie factors)</li><li><strong>Minerals:</strong> calcium, iron, magnesium, phosphorus, potassium, sodium, zinc, copper, manganese, selenium, fluoride</li><li><strong>Vitamins:</strong> A, C, D, E, K, thiamin (B1), riboflavin (B2), niacin (B3), pantothenic acid (B5), B6, folate (B9), B12, choline</li><li><strong>Lipids:</strong> individual fatty acids (saturated, mono, poly), trans fat, cholesterol, phytosterols</li><li><strong>Amino acids:</strong> all 20 standard amino acids for many foods</li><li><strong>Other:</strong> caffeine, theobromine, alcohol, carotenoids, flavonoids (for some foods)</li></ul><p>What USDA does NOT comprehensively track:</p><ul><li><strong>Phytochemicals:</strong> thousands of plant compounds with potential health effects are not in the standard database</li><li><strong>Polyphenols:</strong> only partially tracked (some flavonoids). The Phenol-Explorer database is a better source.</li><li><strong>Glycemic index:</strong> not in USDA databases. The University of Sydney's GI database is the primary source.</li><li><strong>FODMAP content:</strong> not tracked by USDA. Monash University is the primary source.</li><li><strong>Bioavailability:</strong> USDA reports what's in the food, not what your body actually absorbs. Bioavailability varies by food matrix, preparation, and individual factors.</li></ul>`,
      },
    ],
    faqs: [
      { question: 'What is USDA FoodData Central?', answer: 'The USDA\'s integrated food composition database (fdc.nal.usda.gov) containing nutritional data for over 300,000 foods from multiple data types: SR Legacy (lab-analyzed whole foods), FNDDS (as-consumed mixed dishes), Foundation Foods (detailed research data), and Branded Foods (manufacturer-reported label data). Free and publicly accessible.' },
      { question: 'How accurate is the nutrition data in USDA databases?', answer: 'SR Legacy and Foundation Foods are based on laboratory analysis of multiple food samples — very accurate for the foods covered. Branded Foods relies on manufacturer-reported label data, which FDA allows to be within ±20% of actual values. Calories on labels tend to be understated rather than overstated.' },
      { question: 'Why do MyFitnessPal and USDA show different calories?', answer: 'Apps supplement USDA data with user-submitted entries that are frequently inaccurate (wrong serving sizes, outdated formulations, errors). Cronometer is more accurate because it uses USDA data with less user contamination. For best accuracy, use USDA FoodData Central directly or verify app entries against the actual Nutrition Facts label.' },
      { question: 'Can nutrition labels be wrong by 20%?', answer: 'Yes, legally. FDA regulations allow ±20% tolerance on stated calorie and macronutrient values. A food labeled at 200 calories could legally contain 160-240 calories. Research shows labels tend to understate calories, especially for "diet" and "low-calorie" products.' },
      { question: 'Which USDA database should I use for lookups?', answer: 'SR Legacy for raw/whole foods (most accurate, lab-verified). Branded Foods for packaged products (manufacturer-reported). FNDDS for mixed dishes as typically consumed in the US. Foundation Foods for the most detailed research-grade data on a smaller set of foods.' },
      { question: 'Does USDA track glycemic index?', answer: 'No. Glycemic index is not in USDA databases. The University of Sydney maintains the primary GI database. Similarly, FODMAP content (Monash University), comprehensive polyphenol data (Phenol-Explorer), and many phytochemicals are not in USDA databases.' },
    ],
  },
  {
    slug: 'calorie-counting-accuracy',
    title: 'Calorie Counting Accuracy: Why Labels Can Be Off by 20%',
    description: 'The FDA ±20% label tolerance, research on actual label accuracy, the Atwater factor system, and why your calorie tracking app may be less accurate than you think.',
    category: 'Nutrition Science',
    updatedAt: u,
    intro: `<p>The entire premise of calorie counting depends on one assumption: that the calorie numbers on food labels and in tracking apps are reasonably accurate. The reality is messier. FDA allows nutrition labels to be off by 20%. The Atwater calorie factors used since the 1900s are known approximations. And popular tracking apps layer additional errors through user-submitted data and portion estimation. This guide explains where the inaccuracies come from, how large they are, and what this means for people trying to manage their weight through calorie tracking.</p>`,
    sections: [
      {
        heading: 'The FDA ±20% rule',
        html: `<p>FDA's Nutrition Labeling and Education Act (NLEA) requires Nutrition Facts labels on most packaged foods. The accuracy requirement: labeled nutrient values must be within 20% of the actual values as determined by FDA analysis.</p><p>Specifically:</p><ul><li><strong>Calories, total fat, saturated fat, trans fat, cholesterol, sodium, total carbs, sugars, protein:</strong> actual value must be ≤120% of labeled value (can't be more than 20% above label) and ≥80% of labeled value for understatement on some nutrients</li><li><strong>Added sugars, dietary fiber:</strong> similar ±20% tolerance</li><li><strong>Vitamins and minerals:</strong> actual content must be ≥80% of labeled value</li></ul><p>The practical meaning: a bar labeled at 250 calories could legally contain up to 300 calories. Over a full day of eating 2,000 calories from packaged foods, the actual intake could range from 1,600 to 2,400 calories — a 800-calorie swing that exceeds most people's deficit targets.</p><p>FDA enforcement is complaint-driven and rare for minor violations. Most foods are not regularly tested for label compliance. This means the 20% tolerance is more of a theoretical maximum than a rigorously enforced standard.</p>`,
      },
      {
        heading: 'What research shows about actual label accuracy',
        html: `<p>Several studies have tested the actual calorie content of commercially available foods against their labels:</p><ul><li><strong>Urban et al. (2010, JADA):</strong> tested 269 food items from 42 restaurants and 10 frozen food brands. Restaurant foods averaged 18% more calories than stated. Some individual items exceeded labels by 200+ calories.</li><li><strong>Jumpertz et al. (2013):</strong> found systematic under-reporting of calories across food categories.</li><li><strong>Nickols-Richardson et al. (2014):</strong> tested snack foods and found most were within the 20% tolerance, but several exceeded it significantly.</li><li><strong>Allison et al. (2014):</strong> reviewed multiple studies and concluded that calorie labeling errors are common, with a systematic bias toward understating actual calorie content.</li></ul><p>Pattern: foods marketed as "healthy," "light," or "low-calorie" are MORE likely to exceed their stated calorie values than regular products. This may reflect intentional optimism in labeling or formulation variability.</p><p>Restaurant calorie counts are generally less accurate than packaged food labels because portion sizes vary by cook, location, and day. A "400-calorie" restaurant salad may range from 350 to 550 calories depending on how generously the dressing is applied.</p>`,
      },
      {
        heading: 'The Atwater factor system',
        html: `<p>All calorie values on US food labels are calculated using "Atwater factors" — conversion factors that estimate the caloric energy from each macronutrient:</p><ul><li><strong>Protein:</strong> 4 calories per gram</li><li><strong>Carbohydrate:</strong> 4 calories per gram</li><li><strong>Fat:</strong> 9 calories per gram</li><li><strong>Alcohol:</strong> 7 calories per gram</li><li><strong>Fiber:</strong> varies (traditionally 4 cal/g, now often adjusted to 2 cal/g or excluded)</li></ul><p>These factors were developed by Wilbur Atwater in the late 1800s and are known approximations. They assume average digestibility and metabolic efficiency, which varies by food matrix:</p><ul><li><strong>Whole almonds:</strong> actual energy absorbed is about 25% less than Atwater-calculated calories because the fibrous cell walls prevent full digestion</li><li><strong>Highly processed foods:</strong> actual energy absorbed may be higher than Atwater-calculated because processing breaks down food structures, improving digestibility</li><li><strong>High-fiber foods:</strong> Atwater factors overestimate calories because fiber is only partially fermented in the colon (2-3 cal/g, not 4)</li><li><strong>Cooking:</strong> increases energy availability by breaking down starches and proteins, but this is not reflected in label values (which use raw or cooked interchangeably depending on the food)</li></ul><p>The net effect: Atwater factors overestimate calories from whole, unprocessed foods and may underestimate calories from ultra-processed foods. This is a systematic bias that favors people eating whole foods and penalizes those eating processed foods — beyond the nutritional differences themselves.</p>`,
      },
      {
        heading: 'App tracking errors on top of label errors',
        html: `<p>Even with perfect label data, calorie tracking apps add their own layer of error:</p><ol><li><strong>Portion estimation.</strong> Most people estimate portions rather than weighing food. Studies show individuals underestimate portions by 20-50% on average. A "tablespoon" of peanut butter estimated by eye is typically 1.5-2 actual tablespoons.</li><li><strong>User-submitted database errors.</strong> MyFitnessPal's database contains millions of user-submitted entries with known inaccuracies — wrong serving sizes, missing nutrients, outdated products, and duplicate entries with different values.</li><li><strong>Recipe estimation.</strong> Logging a "homemade chicken salad" requires estimating every ingredient and preparation method. Oil absorbed during cooking, evaporation of water, and variable ingredient amounts make recipe logging approximate at best.</li><li><strong>Eating out.</strong> Restaurant portions are not standardized. A "grilled chicken breast" at one restaurant may be 6 oz (280 cal) and at another 10 oz (470 cal).</li></ol><p>Combining label tolerance (±20%), Atwater factor approximation (±10%), portion estimation error (±20-50%), and database errors (variable), the total error in a typical day of calorie tracking can easily reach ±30-50% of actual intake.</p>`,
      },
      {
        heading: 'What this means for weight management',
        html: `<p>If calorie tracking has ±30-50% error, does it still work? The evidence says: yes, but not for the reason most people think.</p><p>Calorie tracking works not because of accuracy but because of <strong>awareness and consistency</strong>:</p><ul><li>People who track calories eat 10-20% less than people who don't, regardless of tracking accuracy</li><li>The act of recording food creates a psychological pause before eating</li><li>Consistency of tracking (using the same database, same estimation methods) creates a reliable relative signal even if absolute numbers are off</li><li>Trends matter more than daily numbers — a consistent "1,800 calorie" day in your app, if consistently tracked, gives you a reliable reference point even if actual intake is 2,100</li></ul><p>Practical implications:</p><ol><li><strong>Don't obsess over exact numbers.</strong> A 200-calorie daily deficit calculated from approximate data is still directionally correct.</li><li><strong>Use a food scale for the first few weeks.</strong> Calibrate your portion estimation by weighing food initially, then transition to estimating.</li><li><strong>Be consistent with your tracking method.</strong> Switching between apps, databases, and estimation methods introduces noise. Pick one system and stick with it.</li><li><strong>Adjust based on real-world results.</strong> If your tracked deficit should produce 1 lb/week loss and you're losing 0.5 lb/week, your actual intake is higher than tracked. Adjust the target down.</li><li><strong>For very precise tracking:</strong> use USDA FoodData Central for whole foods, a food scale for portions, and Cronometer for the app (least user-submitted data contamination).</li></ol>`,
      },
    ],
    faqs: [
      { question: 'How accurate are nutrition labels?', answer: 'FDA allows ±20% tolerance on stated calorie and macronutrient values. Research shows labels tend to understate calories, with restaurant items averaging 18% more than stated. A food labeled at 200 calories could legally contain 160-240 calories.' },
      { question: 'Why do labels understate calories?', answer: 'Two reasons: (1) Atwater calorie factors are approximations that don\'t account for food matrix effects (whole foods are less digestible than calculated; processed foods may be more), and (2) manufacturers have a marketing incentive to present favorable numbers within the legal tolerance.' },
      { question: 'How accurate is MyFitnessPal?', answer: 'For branded products with verified data, reasonably accurate (within label tolerance). For user-submitted entries, frequently inaccurate — wrong serving sizes, missing nutrients, outdated formulations. Cronometer is generally more accurate because it uses USDA data with less user contamination.' },
      { question: 'Does calorie counting still work if labels are inaccurate?', answer: 'Yes, through awareness and consistency rather than absolute accuracy. People who track eat 10-20% less than those who don\'t. Consistent tracking creates a reliable relative signal even if absolute numbers are off. Adjust based on real-world weight trends rather than trusting the numbers blindly.' },
      { question: 'What are Atwater factors?', answer: 'Conversion factors developed in the 1890s to estimate calories from macronutrients: protein 4 cal/g, carbohydrate 4 cal/g, fat 9 cal/g, alcohol 7 cal/g. They are approximations that overestimate calories from whole/high-fiber foods and may underestimate calories from ultra-processed foods.' },
      { question: 'Should I use a food scale?', answer: 'Yes, at least for the first few weeks to calibrate your portion estimation. Studies show people underestimate portions by 20-50%. Weighing food is the single most effective way to improve tracking accuracy. After calibration, you can transition to estimation with better accuracy.' },
    ],
  },
  {
    slug: 'protein-per-dollar',
    title: 'Protein Per Dollar: The Most Cost-Effective Protein Sources Ranked',
    description: 'A data-driven ranking of protein sources by cost efficiency — grams of protein per dollar — with quality adjustments for amino acid profile, digestibility, and practical preparation.',
    category: 'Nutrition Economics',
    updatedAt: u,
    intro: `<p>"How do I get enough protein without spending a fortune?" is one of the most practical nutrition questions. The answer varies enormously depending on the protein source. Chicken breast provides roughly 30 grams of protein per dollar. Grass-fed beef steak provides about 6 grams per dollar — a 5x difference for comparable protein quality. This guide ranks the most common protein sources by cost efficiency, with adjustments for protein quality and practical considerations that the raw numbers don't capture.</p>`,
    sections: [
      {
        heading: 'The ranking: grams of protein per dollar',
        html: `<p>Based on US grocery prices (national average, 2024-2025), ranked by grams of protein per dollar spent:</p><ol><li><strong>Dried lentils / split peas:</strong> ~55-65g protein/$1. By far the cheapest protein source. But plant protein with incomplete amino acid profile (low in methionine).</li><li><strong>Dried beans (pinto, black, kidney):</strong> ~45-55g/$1. Similar to lentils. Incomplete amino acid profile but excellent when combined with rice/grains.</li><li><strong>Eggs (regular, large):</strong> ~35-45g/$1 at typical $3-4/dozen prices. Complete amino acid profile, high digestibility (DIAAS 1.0). One of the best overall value proteins.</li><li><strong>Whole milk:</strong> ~30-40g/$1 at typical $3.50-4.50/gallon. Complete protein, easy to consume. High in calcium and other nutrients.</li><li><strong>Chicken breast (bone-in, skin-on):</strong> ~30-35g/$1 at $2-3/lb. Complete protein, very high digestibility. The gold standard affordable animal protein.</li><li><strong>Canned tuna (chunk light):</strong> ~28-35g/$1. Complete, high-quality protein. Limited by mercury considerations (2-3 cans/week max recommended).</li><li><strong>Cottage cheese:</strong> ~25-30g/$1. Complete protein, high in casein (slow-digesting). Good for satiety.</li><li><strong>Greek yogurt (plain, store brand):</strong> ~20-25g/$1. Complete protein, probiotics. Flavored varieties are much less protein-efficient due to higher price and added sugar.</li><li><strong>Whey protein powder:</strong> ~20-25g/$1 at typical bulk prices. Highest protein quality score (DIAAS ~1.1). Best protein-per-calorie ratio of any source.</li><li><strong>Ground turkey (93% lean):</strong> ~18-22g/$1 at $4-5/lb.</li><li><strong>Chicken thighs (bone-in):</strong> ~22-28g/$1. Fattier than breast but often cheaper. Great flavor and versatility.</li><li><strong>Tofu (firm):</strong> ~20-25g/$1. Complete plant protein (soy is the only legume with a complete amino acid profile). High digestibility.</li><li><strong>Peanut butter:</strong> ~15-20g/$1. Incomplete amino acid profile (low in lysine), high in fat/calories relative to protein.</li><li><strong>Ground beef (80/20):</strong> ~15-18g/$1 at $4-5/lb.</li><li><strong>Salmon (frozen):</strong> ~10-15g/$1 at $6-8/lb. Excellent protein quality plus omega-3s, but expensive per gram of protein.</li><li><strong>Beef steak (sirloin):</strong> ~6-10g/$1 at $8-12/lb. Premium protein, premium price.</li></ol>`,
      },
      {
        heading: 'Protein quality: not all grams are equal',
        html: `<p>Raw grams-per-dollar doesn't account for protein quality, which varies by amino acid profile and digestibility. The DIAAS (Digestible Indispensable Amino Acid Score) is the current gold standard for protein quality assessment (replacing the older PDCAAS):</p><ul><li><strong>DIAAS > 1.0 ("excellent"):</strong> whole milk (1.14), eggs (1.13), whey protein (1.09), chicken breast (1.08), beef (1.10)</li><li><strong>DIAAS 0.75-1.0 ("good"):</strong> soy/tofu (0.90-0.98), pea protein (0.82-0.92)</li><li><strong>DIAAS < 0.75 ("lower quality"):</strong> rice (0.60), wheat (0.45), most beans/lentils when consumed alone (0.55-0.70)</li></ul><p>Lower-DIAAS proteins are not "bad" — they just need to be consumed in larger quantities or combined with complementary proteins to achieve the same amino acid delivery as higher-DIAAS sources. Rice + beans together have a combined DIAAS close to 1.0 because rice provides the methionine that beans lack, and beans provide the lysine that rice lacks.</p><p>Quality-adjusted protein cost recalculation (grams of "high-quality equivalent" protein per dollar):</p><ul><li>Eggs: 35-45g → ~35-45g (DIAAS 1.13, no adjustment needed)</li><li>Lentils: 55-65g → ~35-42g (DIAAS ~0.65, adjusted down by 35%)</li><li>Chicken breast: 30-35g → ~30-35g (DIAAS 1.08)</li><li>Tofu: 20-25g → ~18-23g (DIAAS ~0.90)</li></ul><p>After quality adjustment, eggs, chicken, and milk remain the best overall protein values. Lentils and beans are still excellent but less dominant than raw numbers suggest.</p>`,
      },
      {
        heading: 'The practical preparation factor',
        html: `<p>Cost per gram ignores preparation time, cooking skill, and practical constraints. Adjustments for real life:</p><ul><li><strong>Dried beans/lentils:</strong> cheapest per gram but require soaking (8-12 hours for beans), cooking (30-60 minutes), and produce a large batch. Practical for meal prep; impractical for quick meals.</li><li><strong>Eggs:</strong> fast, versatile, minimal preparation. Extremely practical for any meal.</li><li><strong>Chicken breast:</strong> requires cooking (20-30 minutes), can be dry if overcooked. Meal prep friendly. Raw chicken handling requires food safety care.</li><li><strong>Canned tuna:</strong> ready to eat from the can. Maximum convenience but limited by mercury and taste fatigue.</li><li><strong>Greek yogurt:</strong> grab and go, no prep. Excellent convenience protein.</li><li><strong>Whey protein:</strong> mix and drink in 30 seconds. Highest convenience-to-protein ratio. But liquid protein is less satiating than whole food protein.</li><li><strong>Cottage cheese:</strong> ready to eat, versatile. Similar convenience to yogurt.</li></ul><p>For meal prep lifestyles: dried beans + chicken breast + eggs = the optimally cost-effective protein rotation. For convenience-first: Greek yogurt + whey protein + canned tuna.</p>`,
      },
      {
        heading: 'Budget protein strategy by income level',
        html: `<ul><li><strong>Very tight budget ($50/week for one person):</strong> Dried beans/lentils + rice (together = complete protein), eggs, whole milk, occasional chicken thighs on sale. Can hit 100g+ protein/day for under $3/day.</li><li><strong>Moderate budget ($75-100/week):</strong> Add chicken breast, Greek yogurt, cottage cheese, canned tuna. 120-150g protein/day comfortably.</li><li><strong>Comfortable budget ($100-150/week):</strong> All of the above plus ground turkey, salmon, whey protein, tofu variety. 150g+ easily.</li><li><strong>Optimizing for convenience:</strong> Pre-cooked rotisserie chicken ($1/serving for ~25g protein), protein bars (expensive per gram but extremely convenient), ready-to-drink protein shakes.</li></ul><p>The bottom line: hitting 100g of protein per day on any budget is achievable if you focus on the top 5-6 items on the cost-efficiency list. Protein variety is nice but not necessary for adequate nutrition. A person eating eggs, chicken, beans, and milk daily is nutritionally well-covered for protein.</p>`,
      },
      {
        heading: 'Common protein myths and realities',
        html: `<ul><li><strong>"Plant protein is incomplete."</strong> Partially true: most individual plant proteins are low in one or more essential amino acids. But soy is a complete protein, and combining grains + legumes (rice + beans) creates a complete amino acid profile. You don't need to combine in the same meal — daily complementarity is sufficient.</li><li><strong>"You need 1g of protein per pound of bodyweight."</strong> Overstated. Research supports 0.7-1.0g per pound for athletes and people actively building muscle. For general health, 0.36g per pound (the RDA) is the minimum, and 0.5-0.7g per pound is optimal for most active adults.</li><li><strong>"Protein powder is artificial/unhealthy."</strong> Whey protein is a dairy byproduct with the highest protein quality score (DIAAS 1.09). It's a food, not a synthetic chemical. Quality varies by brand — look for third-party testing (NSF Certified for Sport, Informed Sport).</li><li><strong>"Expensive protein is better."</strong> Grass-fed beef and wild-caught salmon have marginally different fatty acid profiles than conventional alternatives, but the protein quality (amino acid profile, digestibility) is nearly identical. The 3-5x price premium buys marginal nutritional differences.</li></ul>`,
      },
    ],
    faqs: [
      { question: 'What is the cheapest protein source?', answer: 'Dried lentils and split peas at ~55-65 grams of protein per dollar, followed by dried beans (~45-55g/$1) and eggs (~35-45g/$1). After adjusting for protein quality (amino acid profile and digestibility), eggs and chicken breast offer the best overall value among complete proteins.' },
      { question: 'How much protein per dollar does chicken breast provide?', answer: 'About 30-35 grams per dollar at typical US prices of $2-3/lb. Bone-in, skin-on is cheaper per pound than boneless skinless. Chicken breast has excellent protein quality (DIAAS ~1.08) and is one of the most cost-effective complete protein sources.' },
      { question: 'Is plant protein as good as animal protein?', answer: 'Per gram, most plant proteins have lower DIAAS scores (0.55-0.70 for beans/lentils alone) than animal proteins (1.0+). Soy is the exception at DIAAS ~0.90-0.98. Combining complementary plant proteins (rice + beans) achieves DIAAS close to 1.0. Quantity needs to be higher for equivalent amino acid delivery.' },
      { question: 'What is DIAAS?', answer: 'Digestible Indispensable Amino Acid Score — the current standard for measuring protein quality, replacing the older PDCAAS. Scores above 1.0 are "excellent" (milk, eggs, whey, meat), 0.75-1.0 are "good" (soy, pea), below 0.75 are "lower quality" (most grains and legumes alone). Higher DIAAS means more usable amino acids per gram of protein consumed.' },
      { question: 'How can I get 100g protein per day on a budget?', answer: 'Focus on the top cost-efficient sources: 3 eggs (18g) + 8oz chicken breast (50g) + 1 cup cooked lentils (18g) + 1 cup milk (8g) + 1 serving Greek yogurt (15g) = ~109g for about $4-5 total. All from the cheapest tier of protein sources.' },
      { question: 'Is whey protein worth the cost?', answer: 'At ~20-25g protein per dollar, whey is mid-range on cost efficiency but offers the highest protein quality (DIAAS 1.09), the best protein-per-calorie ratio, and maximum convenience. For people struggling to hit protein targets from whole foods alone, whey is one of the most cost-effective supplements.' },
    ],
  },
  {
    slug: 'ultra-processed-foods-nova',
    title: 'Ultra-Processed Foods: What the NOVA Classification Actually Means',
    description: 'How the NOVA food classification system works, what makes a food "ultra-processed," the epidemiological evidence on health outcomes, and why NOVA is both useful and limited.',
    category: 'Food Science',
    updatedAt: u,
    intro: `<p>"Ultra-processed food" has become one of the most discussed terms in nutrition science and media. The NOVA classification system, developed by Carlos Monteiro's group at the University of São Paulo, categorizes all foods into four groups based on the extent and purpose of processing. Group 4 — "ultra-processed foods" — includes products like soft drinks, packaged snacks, instant noodles, and reconstituted meat products. Epidemiological research has linked higher UPF consumption to obesity, cardiovascular disease, cancer, and all-cause mortality. But the classification is also controversial among food scientists. This guide explains the NOVA system, what the research actually shows, and the legitimate criticisms.</p>`,
    sections: [
      {
        heading: 'The 4 NOVA groups',
        html: `<p>NOVA classifies all foods into four groups based on processing extent:</p><ol><li><strong>Group 1 — Unprocessed or minimally processed foods:</strong> the edible parts of plants or animals, or foods altered only by processes like drying, freezing, pasteurization, or fermentation without adding substances. Examples: fresh fruits and vegetables, eggs, fresh meat, milk, plain yogurt, dried beans, rice, flour, frozen vegetables, coffee beans.</li><li><strong>Group 2 — Processed culinary ingredients:</strong> substances extracted from Group 1 foods by pressing, refining, grinding, or milling. Used in cooking but rarely eaten alone. Examples: oils (olive, coconut, vegetable), butter, sugar, salt, honey, flour, starch.</li><li><strong>Group 3 — Processed foods:</strong> Group 1 foods modified by Group 2 ingredients through simple methods like canning, bottling, or fermenting. Recognizable as modified versions of the original food. Examples: canned vegetables, canned fish, cheese, bread (simple recipe), preserved meats, beer, wine.</li><li><strong>Group 4 — Ultra-processed foods (UPF):</strong> industrial formulations of substances derived from foods and additives, with little or no intact Group 1 food. Designed for convenience, palatability, and long shelf life. Examples: soft drinks, packaged chips, instant noodles, frozen pizza, hot dogs, most breakfast cereals, flavored yogurt, protein bars, ready-to-eat meals.</li></ol><p>The distinguishing features of Group 4 are: (1) ingredients you wouldn't find in a home kitchen (high-fructose corn syrup, hydrogenated oils, modified starches, emulsifiers, flavor enhancers) and (2) industrial processing techniques not used in domestic cooking.</p>`,
      },
      {
        heading: 'How much UPF Americans eat',
        html: `<p>NHANES (National Health and Nutrition Examination Survey) data shows that ultra-processed foods account for approximately:</p><ul><li><strong>57-60% of total calorie intake</strong> for the average American adult</li><li><strong>67% of total calorie intake</strong> for American children and adolescents</li><li><strong>90% of added sugar intake</strong> comes from ultra-processed foods</li></ul><p>The proportion has been rising over time. In the 1980s, UPFs accounted for roughly 50% of calories; by 2018 it had risen to 57-60%.</p><p>Country comparison:</p><ul><li>US: ~57-60% of calories from UPF</li><li>UK: ~55%</li><li>Canada: ~48%</li><li>France: ~36%</li><li>Brazil: ~20%</li><li>Japan: ~25%</li></ul><p>The US, UK, Canada, and Australia have the highest UPF consumption globally. Mediterranean and East Asian dietary patterns have the lowest.</p>`,
      },
      {
        heading: 'The epidemiological evidence',
        html: `<p>A large and growing body of epidemiological research links UPF consumption to adverse health outcomes. Key studies:</p><ul><li><strong>NutriNet-Santé cohort (France, 100K+ participants):</strong> 10% increase in UPF intake associated with 12% higher cancer risk (Fiolet et al., BMJ 2018), 12% higher cardiovascular disease risk (Srour et al., BMJ 2019), and higher all-cause mortality.</li><li><strong>NHANES analysis (US):</strong> highest UPF consumers had significantly higher rates of obesity, metabolic syndrome, and cardiovascular mortality.</li><li><strong>UK Biobank (200K+ participants):</strong> higher UPF consumption associated with 29% higher risk of dementia (Li et al., Neurology 2022) and 9% higher cancer mortality per 10% increase in UPF calories.</li><li><strong>Hall et al. (NIH, 2019, the only RCT):</strong> the landmark randomized controlled trial. 20 participants given either UPF or unprocessed diet for 2 weeks, then switched. On the UPF diet, participants spontaneously ate 500 more calories per day and gained 2 pounds. On the unprocessed diet, they lost 2 pounds. Both diets were matched for calories, macronutrients, and fiber available.</li></ul><p>The Hall study is critically important because it's the only RCT — all other evidence is observational. The finding that UPF diets cause spontaneous overconsumption suggests a causal mechanism, not just correlation.</p>`,
      },
      {
        heading: 'Why UPFs may cause harm',
        html: `<p>Several mechanisms have been proposed for why ultra-processed foods affect health differently from less-processed alternatives:</p><ol><li><strong>Hyper-palatability.</strong> UPFs are engineered for optimal taste through combinations of sugar + fat + salt that rarely occur in nature. This drives overconsumption beyond satiety signals.</li><li><strong>Food matrix disruption.</strong> Processing breaks down the physical structure of foods, increasing the speed of digestion and absorption. A whole apple produces a different glycemic and satiety response than apple juice with the same calories.</li><li><strong>Low satiety per calorie.</strong> UPFs tend to have low fiber, low water content, and soft textures that require less chewing — all factors that reduce satiety signals. The Hall study showed people simply ate more when given UPFs.</li><li><strong>Additives.</strong> Emulsifiers (carboxymethylcellulose, polysorbate-80), artificial sweeteners, and modified starches have shown adverse effects on gut microbiome in animal and some human studies. Evidence is emerging but not conclusive.</li><li><strong>Nutrient displacement.</strong> Calories from UPFs replace calories from whole foods. Higher UPF intake correlates with lower intake of fruits, vegetables, legumes, and whole grains.</li></ol>`,
      },
      {
        heading: 'The criticisms of NOVA',
        html: `<p>NOVA is not universally accepted in food science. Legitimate criticisms:</p><ol><li><strong>Heterogeneity within Group 4.</strong> "Ultra-processed" lumps together soft drinks and whole-grain bread with added emulsifiers. A multigrain breakfast cereal fortified with vitamins is classified alongside candy bars. The group is too broad to be nutritionally meaningful for many products.</li><li><strong>Processing ≠ unhealthy.</strong> Pasteurization, fortification, and fermentation are all forms of processing that improve food safety and nutrition. Some "ultra-processed" foods (fortified cereals, plant-based milks, protein bars) are nutritionally designed to fill dietary gaps.</li><li><strong>Confounding in observational studies.</strong> People who eat more UPFs also tend to have other risk factors: lower income, less physical activity, more smoking, less healthcare access. While studies adjust for these, residual confounding is hard to eliminate.</li><li><strong>No clear mechanism for the classification itself.</strong> The harmful effects may be driven by specific properties (high calorie density, low fiber, specific additives) rather than "processing" per se. A nutrient-profiling approach (scoring foods by actual nutrient content) may be more predictive than a processing-based classification.</li><li><strong>Practical limitations.</strong> Telling people to "avoid ultra-processed foods" is impractical when 57% of American calories come from UPFs. A more nuanced approach (distinguish harmful UPFs from benign ones) would be more useful.</li></ol>`,
      },
      {
        heading: 'A practical approach',
        html: `<p>Given both the evidence and the criticisms, a balanced practical approach:</p><ol><li><strong>Don't obsess over NOVA classification.</strong> Not all UPFs are equally harmful. Plain Greek yogurt with added thickeners (technically UPF) is nutritionally excellent. A sugar-sweetened soda (also UPF) is nutritionally empty. The classification is a useful starting point, not a final answer.</li><li><strong>Focus on displacement.</strong> The biggest problem with UPFs is what they replace. If increasing UPF intake means eating fewer fruits, vegetables, legumes, and whole grains, that's the real issue.</li><li><strong>Read ingredient lists.</strong> Products with short ingredient lists of recognizable foods are generally healthier than those with long lists of unrecognizable additives — regardless of NOVA classification.</li><li><strong>Reduce sugar-sweetened beverages first.</strong> The single highest-impact change. Liquid calories from soda and sweetened drinks are the most clearly harmful UPF category.</li><li><strong>Cook more.</strong> Home cooking naturally reduces UPF intake because home cooks use Group 1-3 ingredients. Even simple cooking (scrambled eggs, rice and beans, pasta with canned tomatoes) dramatically reduces reliance on Group 4 products.</li></ol>`,
      },
    ],
    faqs: [
      { question: 'What is an ultra-processed food?', answer: 'Under the NOVA classification system, ultra-processed foods (Group 4) are industrial formulations made from substances derived from foods and additives not used in home cooking. They include soft drinks, chips, instant noodles, frozen pizza, hot dogs, most breakfast cereals, and many packaged snacks. Key features: industrial additives, engineered palatability, long shelf life.' },
      { question: 'How much of the American diet is ultra-processed?', answer: 'About 57-60% of total calories for adults and 67% for children, according to NHANES data. The US has among the highest UPF consumption globally, alongside the UK, Canada, and Australia.' },
      { question: 'Does ultra-processed food cause obesity?', answer: 'The strongest evidence comes from the Hall NIH 2019 RCT: when given UPF versus unprocessed diets matched for available calories, participants spontaneously ate 500 more calories per day on UPFs and gained weight. Observational studies consistently link UPF consumption to higher BMI and obesity risk. The evidence supports causation, not just correlation.' },
      { question: 'Is all ultra-processed food bad?', answer: 'No. NOVA Group 4 is very heterogeneous — it includes both soda (clearly harmful) and fortified whole-grain cereals (potentially beneficial). The classification groups too many different products together to make blanket "good/bad" judgments. Focus on specific food properties (fiber, sugar, calorie density) rather than processing category alone.' },
      { question: 'What is the NOVA classification?', answer: 'A food classification system developed at the University of São Paulo that categorizes all foods into 4 groups based on processing: Group 1 (unprocessed), Group 2 (culinary ingredients), Group 3 (processed), Group 4 (ultra-processed). Used widely in nutrition research and by governments (Brazil, France) for dietary guidelines.' },
      { question: 'Should I avoid all ultra-processed foods?', answer: 'Impractical and unnecessary. A better approach: reduce sugar-sweetened beverages (highest-impact change), cook more meals from whole ingredients, read ingredient lists for recognizable foods, and focus on not displacing fruits/vegetables/legumes/whole grains with UPFs. Some technically "ultra-processed" foods (fortified cereals, plant milks, protein bars) can be part of a healthy diet.' },
    ],
  },
  {
    slug: 'daily-value-vs-rda',
    title: 'Daily Value vs RDA: Reading Nutrition Labels Without Getting Fooled',
    description: 'The difference between Daily Value (on labels) and RDA (the scientific recommendation), how %DV is calculated, the 2,000 calorie reference, and what the percentages actually mean for your diet.',
    category: 'Label Reading',
    updatedAt: u,
    intro: `<p>The "% Daily Value" column on every Nutrition Facts label is the most misunderstood number in American nutrition. Most consumers assume it tells them what percentage of their daily needs they're getting. It doesn't — it tells them the percentage of a reference amount that may or may not match their actual needs. The Daily Value (DV) is set by FDA for labeling purposes and is not the same as the Recommended Dietary Allowance (RDA) set by the National Academies for health guidance. The two differ for several nutrients. This guide explains exactly what %DV means, how it differs from RDA, and how to actually use labels to make informed food choices.</p>`,
    sections: [
      {
        heading: 'Daily Value vs RDA: the key difference',
        html: `<p>Two different numbers, set by different organizations, for different purposes:</p><ul><li><strong>Daily Value (DV):</strong> set by FDA for food labeling purposes. A single reference value used for ALL adults and children 4+ regardless of age, sex, or activity level. Used to calculate the %DV on Nutrition Facts labels.</li><li><strong>Recommended Dietary Allowance (RDA):</strong> set by the National Academies (formerly Institute of Medicine) as the daily intake sufficient to meet the needs of 97-98% of healthy individuals. Varies by age, sex, pregnancy status, and lactation.</li></ul><p>Example: Vitamin C</p><ul><li>DV (FDA, for labeling): 90 mg</li><li>RDA for men 19+: 90 mg</li><li>RDA for women 19+: 75 mg</li><li>RDA for pregnant women: 85 mg</li><li>RDA for smokers: add 35 mg</li></ul><p>For Vitamin C, the DV matches the adult male RDA. But for a non-smoking woman, the DV overstates her needs by 20%. For a male smoker, the DV understates needs by 39%.</p><p>The DV is a compromise — a single number used for simplicity on labels, not a personalized recommendation. The RDA is the personalized target based on your demographic.</p>`,
      },
      {
        heading: 'The 2,000 calorie reference diet',
        html: `<p>The %DV on labels is calculated based on a 2,000 calorie daily diet. This reference was set by FDA in 1993 based on calorie surveys of the American population.</p><p>The 2,000 calorie reference is not right for most Americans:</p><ul><li><strong>Average sedentary woman:</strong> needs about 1,600-2,000 calories/day</li><li><strong>Average sedentary man:</strong> needs about 2,000-2,400 calories/day</li><li><strong>Active young adults:</strong> may need 2,500-3,500 calories/day</li><li><strong>Children:</strong> need 1,200-2,200 depending on age</li><li><strong>Older sedentary adults:</strong> may need 1,400-1,800 calories/day</li></ul><p>If your actual calorie need is 1,600 (common for a smaller sedentary woman), a food showing "15% DV" for a nutrient actually provides about 19% of YOUR daily need (because you eat 20% fewer total calories). Conversely, if your need is 2,800 calories (common for an active man), that 15% DV covers only about 11% of YOUR need.</p><p>Bottom line: %DV is approximate for the "average" adult. Adjust mentally based on whether you eat more or less than 2,000 calories.</p>`,
      },
      {
        heading: 'How to actually use %DV',
        html: `<p>FDA's simple guidance:</p><ul><li><strong>5% DV or less = low:</strong> a small amount of that nutrient per serving</li><li><strong>20% DV or more = high:</strong> a significant amount</li></ul><p>How to apply this:</p><ul><li><strong>For nutrients to limit (sodium, saturated fat, added sugars):</strong> choose foods with LOW %DV (5% or less per serving)</li><li><strong>For nutrients to get enough of (fiber, vitamin D, calcium, iron, potassium):</strong> choose foods with HIGH %DV (20% or more per serving)</li></ul><p>Quick math for the day: if you eat roughly 2,000 calories from a mix of foods, and your foods average around 100% DV for each nutrient across the day, you're meeting the reference targets. You don't need 100% from any single food — the %DV is designed to add up across all foods eaten in a day.</p><p>The 5%/20% rule is surprisingly powerful for quick label comparisons. Scanning the %DV column takes seconds and immediately identifies whether a food is a meaningful source of nutrients you need or a contributor to nutrients you're trying to limit.</p>`,
      },
      {
        heading: 'Where DV and RDA diverge significantly',
        html: `<p>For some nutrients, the DV and RDA are quite different, creating practical confusion:</p><p><strong>Sodium:</strong></p><ul><li>DV: 2,300 mg (the basis for %DV on labels)</li><li>AHA recommendation: under 1,500 mg for most adults</li><li>Average American intake: ~3,400 mg/day</li><li>Implication: a food showing "10% DV sodium" (230 mg) is actually 15% of the AHA recommendation</li></ul><p><strong>Fiber:</strong></p><ul><li>DV: 28g (used for %DV)</li><li>RDA for men 19-50: 38g</li><li>RDA for women 19-50: 25g</li><li>Average American intake: 15g/day</li><li>Implication: a man looking at %DV for fiber is underestimating his actual need by 36%</li></ul><p><strong>Protein:</strong></p><ul><li>DV: 50g (used for %DV)</li><li>RDA: 0.8g per kg body weight (56g for average man, 46g for average woman)</li><li>Optimal for active adults: 1.2-2.0g per kg</li><li>Implication: the DV is close to the minimum RDA but well below what active adults and researchers recommend</li></ul><p><strong>Calcium:</strong></p><ul><li>DV: 1,300 mg</li><li>RDA for adults 19-50: 1,000 mg</li><li>RDA for women 51+ and men 71+: 1,200 mg</li><li>Implication: for most adults under 50, the DV overstates calcium needs by 30%</li></ul>`,
      },
      {
        heading: 'The nutrients labels don\'t show',
        html: `<p>Nutrition Facts labels are required to show only a specific set of nutrients. Several important ones are missing:</p><ul><li><strong>Omega-3 fatty acids (EPA/DHA):</strong> not required on labels. No established DV. Recommended intake: 250-500 mg/day of combined EPA+DHA from expert bodies.</li><li><strong>Vitamin K:</strong> not required on labels (only voluntarily disclosed). DV: 120 mcg. Important for blood clotting and bone health.</li><li><strong>Magnesium:</strong> not required. DV: 420 mg. Widely under-consumed (about 50% of Americans don't meet the RDA).</li><li><strong>Zinc:</strong> not required. DV: 11 mg. Important for immune function.</li><li><strong>Choline:</strong> not required. Adequate Intake: 550 mg men, 425 mg women. Important for liver and brain function.</li></ul><p>For these nutrients, you need to look them up in USDA FoodData Central or use a comprehensive tracking app (Cronometer tracks all of these).</p>`,
      },
      {
        heading: 'Label reading shortcuts for busy shoppers',
        html: `<ol><li><strong>Check serving size first.</strong> "110 calories per serving" means nothing if the bag contains 6 servings and you eat the whole thing. Companies use unrealistically small serving sizes to make nutrition numbers look better.</li><li><strong>Scan %DV column for extremes.</strong> Anything over 20% is high (good for fiber, vitamins; bad for sodium, saturated fat). Anything under 5% is low.</li><li><strong>Check added sugars.</strong> FDA now requires "Added Sugars" as a separate line. The DV for added sugars is 50g (about 12 teaspoons). A single can of soda provides 39g (78% DV) of added sugars.</li><li><strong>Compare the ingredient list length.</strong> Shorter lists with recognizable ingredients generally indicate less processing and fewer additives.</li><li><strong>Ignore front-of-package claims.</strong> "Natural," "healthy," "light," and similar marketing terms are loosely regulated. The Nutrition Facts label and ingredient list are the legally required information.</li></ol>`,
      },
    ],
    faqs: [
      { question: 'What is the difference between Daily Value and RDA?', answer: 'Daily Value (DV) is set by FDA for food labels — a single reference value for all adults used to calculate %DV. RDA (Recommended Dietary Allowance) is set by the National Academies as the scientifically determined intake for 97-98% of healthy individuals, varying by age, sex, and life stage. They often differ for specific nutrients.' },
      { question: 'What does 20% Daily Value mean?', answer: 'One serving of that food provides 20% of the FDA\'s reference daily amount for that nutrient. FDA considers 20%+ "high" and 5% or less "low." The reference is based on a 2,000 calorie diet — if you eat more or less, adjust proportionally.' },
      { question: 'Is the 2,000 calorie reference accurate for me?', answer: 'Probably not exactly. 2,000 calories is close to the need of an average sedentary woman or a lightly active older adult. Sedentary smaller women may need 1,600; active men may need 2,500-3,000. If your calorie need differs, the %DV is directionally useful but not precisely calibrated to you.' },
      { question: 'Why don\'t labels show all vitamins and minerals?', answer: 'FDA only requires specific nutrients on the Nutrition Facts label. Missing nutrients include omega-3 fatty acids, vitamin K, magnesium, zinc, and choline — all important for health. For these, use USDA FoodData Central or a comprehensive tracking app like Cronometer.' },
      { question: 'How do I use labels to eat healthier?', answer: 'Check serving size first (is it realistic?). Scan %DV for fiber, vitamins D and calcium (look for HIGH, 20%+). Check sodium and added sugars (look for LOW, 5% or less). Compare ingredient list length — shorter with recognizable ingredients is generally better. Ignore front-of-package marketing claims.' },
      { question: 'What is the DV for protein?', answer: '50g on current labels. This is close to the minimum RDA but well below what researchers recommend for active adults (0.7-1.0g per pound of body weight). For most active adults, the DV understates protein needs by 40-100%.' },
    ],
  },
];

export function getAllGuides(): Guide[] {
  return guides;
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
