/**
 * US state-level food & nutrition data — obesity rates, popular local cuisines,
 * farmers markets, and dietary trends. Sources: CDC BRFSS, USDA Farmers Market
 * Directory, state health department reports.
 */

export interface StateData {
  slug: string;
  name: string;
  code: string;
  obesityRate: number;          // % adults, CDC BRFSS 2023
  popularCuisines: string[];    // 3-5 iconic local foods
  farmersMarkets: number;       // USDA directory count
  dietaryTrends: string[];      // 2-3 notable dietary patterns
}

export const states: StateData[] = [
  { slug: 'alabama', name: 'Alabama', code: 'AL', obesityRate: 39.1, popularCuisines: ['Fried catfish', 'BBQ pulled pork', 'Pecan pie', 'Biscuits and gravy'], farmersMarkets: 148, dietaryTrends: ['High fried food consumption', 'Growing farm-to-table movement', 'Low vegetable intake'] },
  { slug: 'alaska', name: 'Alaska', code: 'AK', obesityRate: 30.4, popularCuisines: ['Wild salmon', 'King crab', 'Reindeer sausage', 'Akutaq (Eskimo ice cream)'], farmersMarkets: 42, dietaryTrends: ['High seafood intake', 'Wild game consumption', 'Limited fresh produce access in rural areas'] },
  { slug: 'arizona', name: 'Arizona', code: 'AZ', obesityRate: 30.7, popularCuisines: ['Sonoran hot dogs', 'Chimichangas', 'Navajo fry bread', 'Prickly pear cactus'], farmersMarkets: 167, dietaryTrends: ['Strong Southwestern and Mexican cuisine influence', 'Growing health-conscious urban dining', 'High consumption of chili peppers'] },
  { slug: 'arkansas', name: 'Arkansas', code: 'AR', obesityRate: 40.6, popularCuisines: ['Fried pickles', 'Possum pie', 'Chocolate gravy', 'Catfish'], farmersMarkets: 124, dietaryTrends: ['High sugar-sweetened beverage consumption', 'Traditional Southern comfort food', 'Expanding local food networks'] },
  { slug: 'california', name: 'California', code: 'CA', obesityRate: 26.8, popularCuisines: ['Avocado toast', 'Fish tacos', 'Cioppino', 'In-N-Out burgers', 'Artisan sourdough'], farmersMarkets: 827, dietaryTrends: ['High plant-based diet adoption', 'Farm-to-fork movement leader', 'Diverse international cuisine influence'] },
  { slug: 'colorado', name: 'Colorado', code: 'CO', obesityRate: 24.2, popularCuisines: ['Green chile', 'Rocky Mountain oysters', 'Bison burgers', 'Craft beer pairings'], farmersMarkets: 198, dietaryTrends: ['Lowest obesity rate consistently', 'Active outdoor lifestyle culture', 'High organic food consumption'] },
  { slug: 'connecticut', name: 'Connecticut', code: 'CT', obesityRate: 28.6, popularCuisines: ['New Haven-style pizza', 'Lobster rolls', 'Steamed cheeseburgers', 'Apple cider donuts'], farmersMarkets: 154, dietaryTrends: ['Farm-to-table dining culture', 'High seafood consumption', 'Growing ethnic food diversity'] },
  { slug: 'delaware', name: 'Delaware', code: 'DE', obesityRate: 33.5, popularCuisines: ['Scrapple', 'Blue crab', 'Slippery dumplings', 'Capriotti subs'], farmersMarkets: 48, dietaryTrends: ['Mid-Atlantic comfort food traditions', 'Strong poultry industry influence', 'Growing local food movement'] },
  { slug: 'florida', name: 'Florida', code: 'FL', obesityRate: 28.4, popularCuisines: ['Key lime pie', 'Stone crab claws', 'Cuban sandwiches', 'Conch fritters', 'Gator tail'], farmersMarkets: 548, dietaryTrends: ['Caribbean and Latin American cuisine fusion', 'High citrus consumption', 'Diverse immigrant food cultures'] },
  { slug: 'georgia', name: 'Georgia', code: 'GA', obesityRate: 33.9, popularCuisines: ['Peach cobbler', 'Fried green tomatoes', 'Boiled peanuts', 'Brunswick stew'], farmersMarkets: 225, dietaryTrends: ['Traditional Southern cooking heritage', 'Atlanta emerging food scene', 'High sweet tea consumption'] },
  { slug: 'hawaii', name: 'Hawaii', code: 'HI', obesityRate: 25.0, popularCuisines: ['Poke bowls', 'Spam musubi', 'Plate lunch', 'Loco moco', 'Haupia'], farmersMarkets: 102, dietaryTrends: ['Asian-Pacific fusion cuisine', 'High fresh fish consumption', 'Year-round tropical fruit availability'] },
  { slug: 'idaho', name: 'Idaho', code: 'ID', obesityRate: 31.0, popularCuisines: ['Baked potatoes', 'Finger steaks', 'Huckleberry everything', 'Trout'], farmersMarkets: 86, dietaryTrends: ['Heavy potato-based diet', 'Growing organic farming sector', 'Ranch-style meat consumption'] },
  { slug: 'illinois', name: 'Illinois', code: 'IL', obesityRate: 31.1, popularCuisines: ['Chicago deep-dish pizza', 'Italian beef sandwiches', 'Chicago-style hot dogs', 'Garrett popcorn'], farmersMarkets: 363, dietaryTrends: ['Urban-rural nutrition divide', 'Strong ethnic food diversity in Chicago', 'Midwest comfort food traditions'] },
  { slug: 'indiana', name: 'Indiana', code: 'IN', obesityRate: 36.6, popularCuisines: ['Pork tenderloin sandwich', 'Sugar cream pie', 'Corn on the cob', 'Persimmon pudding'], farmersMarkets: 222, dietaryTrends: ['High processed food consumption', 'Strong agricultural tradition', 'Growing local food movement'] },
  { slug: 'iowa', name: 'Iowa', code: 'IA', obesityRate: 36.1, popularCuisines: ['Loose meat sandwiches', 'Iowa pork chops', 'Sweet corn', 'Scotcheroos'], farmersMarkets: 215, dietaryTrends: ['Corn and soybean production influence', 'Traditional Midwestern comfort food', 'High red meat consumption'] },
  { slug: 'kansas', name: 'Kansas', code: 'KS', obesityRate: 34.4, popularCuisines: ['Kansas City BBQ', 'Bierocks', 'Fried chicken', 'Wheat bread'], farmersMarkets: 143, dietaryTrends: ['High red meat and wheat consumption', 'BBQ culture influence', 'Limited fresh produce in western counties'] },
  { slug: 'kentucky', name: 'Kentucky', code: 'KY', obesityRate: 38.0, popularCuisines: ['Hot Brown sandwich', 'Burgoo stew', 'Bourbon balls', 'Beer cheese'], farmersMarkets: 178, dietaryTrends: ['High soda consumption', 'Traditional Appalachian cooking', 'Growing bourbon food pairings'] },
  { slug: 'louisiana', name: 'Louisiana', code: 'LA', obesityRate: 38.1, popularCuisines: ['Gumbo', 'Crawfish boil', 'Beignets', 'Po-boys', 'Jambalaya'], farmersMarkets: 139, dietaryTrends: ['Rich Cajun and Creole cooking traditions', 'High sodium in traditional dishes', 'Unique spice-heavy cuisine culture'] },
  { slug: 'maine', name: 'Maine', code: 'ME', obesityRate: 30.8, popularCuisines: ['Lobster rolls', 'Blueberry pie', 'Clam chowder', 'Whoopie pies'], farmersMarkets: 112, dietaryTrends: ['Strong seafood economy', 'High farm-to-table adoption', 'Growing organic farming sector'] },
  { slug: 'maryland', name: 'Maryland', code: 'MD', obesityRate: 31.3, popularCuisines: ['Maryland crab cakes', 'Old Bay everything', 'Smith Island cake', 'Pit beef'], farmersMarkets: 181, dietaryTrends: ['Chesapeake Bay seafood traditions', 'Diverse suburban food culture', 'High sodium in traditional preparations'] },
  { slug: 'massachusetts', name: 'Massachusetts', code: 'MA', obesityRate: 27.1, popularCuisines: ['Clam chowder', 'Boston cream pie', 'Lobster rolls', 'Baked beans'], farmersMarkets: 279, dietaryTrends: ['Health-conscious urban population', 'Strong local food movement', 'High restaurant density and diverse cuisines'] },
  { slug: 'michigan', name: 'Michigan', code: 'MI', obesityRate: 34.6, popularCuisines: ['Detroit-style pizza', 'Pasties', 'Cherry pies', 'Coney Island hot dogs'], farmersMarkets: 323, dietaryTrends: ['Automotive industry diet legacy', 'Growing urban farming movement (Detroit)', 'Great Lakes fish traditions'] },
  { slug: 'minnesota', name: 'Minnesota', code: 'MN', obesityRate: 30.3, popularCuisines: ['Tater tot hotdish', 'Juicy Lucy burgers', 'Wild rice soup', 'Lefse'], farmersMarkets: 214, dietaryTrends: ['Scandinavian food traditions', 'High dairy consumption', 'Strong cooperative food movement'] },
  { slug: 'mississippi', name: 'Mississippi', code: 'MS', obesityRate: 40.1, popularCuisines: ['Delta tamales', 'Catfish po-boys', 'Comeback sauce', 'Mud pie'], farmersMarkets: 96, dietaryTrends: ['Highest obesity rate in many years', 'Limited healthy food access (food deserts)', 'Traditional soul food cooking'] },
  { slug: 'missouri', name: 'Missouri', code: 'MO', obesityRate: 34.8, popularCuisines: ['St. Louis-style ribs', 'Toasted ravioli', 'Gooey butter cake', 'Kansas City BBQ'], farmersMarkets: 224, dietaryTrends: ['BBQ culture rivalry (KC vs Memphis style)', 'Midwest comfort food', 'Growing craft food scene'] },
  { slug: 'montana', name: 'Montana', code: 'MT', obesityRate: 28.1, popularCuisines: ['Bison steaks', 'Huckleberry jam', 'Rocky Mountain trout', 'Elk burgers'], farmersMarkets: 72, dietaryTrends: ['High wild game consumption', 'Ranch-based diets', 'Growing organic and sustainable farming'] },
  { slug: 'nebraska', name: 'Nebraska', code: 'NE', obesityRate: 34.1, popularCuisines: ['Runza sandwiches', 'Corn-fed beef steaks', 'Kolaches', 'Dorothy Lynch dressing'], farmersMarkets: 128, dietaryTrends: ['High beef consumption per capita', 'Strong agricultural diet traditions', 'Czech and German food heritage'] },
  { slug: 'nevada', name: 'Nevada', code: 'NV', obesityRate: 28.7, popularCuisines: ['Las Vegas buffets', 'Basque lamb', 'Shrimp cocktails', 'All-you-can-eat sushi'], farmersMarkets: 54, dietaryTrends: ['Vegas dining culture influence', 'Limited water for agriculture', 'Diverse international food scene'] },
  { slug: 'new-hampshire', name: 'New Hampshire', code: 'NH', obesityRate: 29.1, popularCuisines: ['Maple syrup', 'Apple cider donuts', 'Boiled dinner', 'Fried clams'], farmersMarkets: 96, dietaryTrends: ['Strong local food traditions', 'High maple product consumption', 'New England seafood access'] },
  { slug: 'new-jersey', name: 'New Jersey', code: 'NJ', obesityRate: 27.9, popularCuisines: ['Taylor ham/pork roll', 'Tomato pie', 'Disco fries', 'Salt water taffy', 'Italian subs'], farmersMarkets: 213, dietaryTrends: ['Dense ethnic food diversity', 'Garden State produce traditions', 'High Italian-American food influence'] },
  { slug: 'new-mexico', name: 'New Mexico', code: 'NM', obesityRate: 31.7, popularCuisines: ['Green chile cheeseburgers', 'Sopapillas', 'Posole', 'Carne adovada', 'Blue corn tortillas'], farmersMarkets: 91, dietaryTrends: ['Strong Native American and Hispanic food heritage', 'High chile pepper consumption', 'Growing local food sovereignty movements'] },
  { slug: 'new-york', name: 'New York', code: 'NY', obesityRate: 28.0, popularCuisines: ['New York-style pizza', 'Bagels', 'Cheesecake', 'Buffalo wings', 'Pastrami sandwiches'], farmersMarkets: 686, dietaryTrends: ['Extreme urban-rural nutrition divide', 'World-class international dining scene', 'High health food awareness in NYC'] },
  { slug: 'north-carolina', name: 'North Carolina', code: 'NC', obesityRate: 33.6, popularCuisines: ['Lexington-style BBQ', 'Krispy Kreme donuts', 'Livermush', 'Sweet potatoes'], farmersMarkets: 268, dietaryTrends: ['Vinegar-based BBQ tradition', 'Growing craft brewery food scene', 'Research Triangle health food expansion'] },
  { slug: 'north-dakota', name: 'North Dakota', code: 'ND', obesityRate: 33.3, popularCuisines: ['Knoephla soup', 'Kuchen', 'Fleischkuekle', 'Lutefisk'], farmersMarkets: 57, dietaryTrends: ['German-Russian food traditions', 'High wheat and grain consumption', 'Limited fresh produce access in winter'] },
  { slug: 'ohio', name: 'Ohio', code: 'OH', obesityRate: 35.5, popularCuisines: ['Cincinnati chili', 'Buckeyes candy', 'Pierogies', 'Sauerkraut balls'], farmersMarkets: 298, dietaryTrends: ['Strong Eastern European food influence', 'Midwest comfort food traditions', 'Growing urban food renaissance'] },
  { slug: 'oklahoma', name: 'Oklahoma', code: 'OK', obesityRate: 38.4, popularCuisines: ['Chicken-fried steak', 'Fried okra', 'Fried pies', 'Onion burgers'], farmersMarkets: 102, dietaryTrends: ['High fried food consumption', 'Native American food traditions', 'Limited healthy food retail in rural areas'] },
  { slug: 'oregon', name: 'Oregon', code: 'OR', obesityRate: 29.5, popularCuisines: ['Marionberry pie', 'Dungeness crab', 'Voodoo Doughnuts', 'Craft beer and food trucks'], farmersMarkets: 286, dietaryTrends: ['Strong organic and sustainable food culture', 'High plant-based diet adoption', 'Food truck innovation hub'] },
  { slug: 'pennsylvania', name: 'Pennsylvania', code: 'PA', obesityRate: 32.8, popularCuisines: ['Philly cheesesteaks', 'Soft pretzels', 'Shoofly pie', 'Scrapple', 'Pierogies'], farmersMarkets: 389, dietaryTrends: ['Pennsylvania Dutch food heritage', 'Strong Italian-American food traditions', 'Growing Amish farm-to-table market'] },
  { slug: 'rhode-island', name: 'Rhode Island', code: 'RI', obesityRate: 29.3, popularCuisines: ['Stuffies', 'Del\'s frozen lemonade', 'Johnnycakes', 'Coffee milk'], farmersMarkets: 54, dietaryTrends: ['Italian-American and Portuguese food influence', 'Strong seafood culture', 'High coffee milk consumption'] },
  { slug: 'south-carolina', name: 'South Carolina', code: 'SC', obesityRate: 35.4, popularCuisines: ['Shrimp and grits', 'She-crab soup', 'Frogmore stew', 'Mustard BBQ'], farmersMarkets: 177, dietaryTrends: ['Lowcountry cuisine traditions', 'High comfort food consumption', 'Charleston food renaissance'] },
  { slug: 'south-dakota', name: 'South Dakota', code: 'SD', obesityRate: 31.9, popularCuisines: ['Chislic', 'Indian tacos', 'Kuchen', 'Pheasant'], farmersMarkets: 56, dietaryTrends: ['High red meat and game consumption', 'Native American food traditions', 'Limited fresh produce access'] },
  { slug: 'tennessee', name: 'Tennessee', code: 'TN', obesityRate: 37.0, popularCuisines: ['Nashville hot chicken', 'Memphis BBQ', 'Moon Pies', 'Goo Goo Clusters'], farmersMarkets: 192, dietaryTrends: ['Strong BBQ and hot chicken culture', 'High sweet tea consumption', 'Growing Nashville food scene'] },
  { slug: 'texas', name: 'Texas', code: 'TX', obesityRate: 34.8, popularCuisines: ['Texas brisket', 'Tex-Mex', 'Chicken-fried steak', 'Kolaches', 'Breakfast tacos'], farmersMarkets: 451, dietaryTrends: ['Strong BBQ and Tex-Mex culture', 'High meat consumption per capita', 'Growing Asian and international food diversity'] },
  { slug: 'utah', name: 'Utah', code: 'UT', obesityRate: 27.0, popularCuisines: ['Fry sauce', 'Funeral potatoes', 'Jell-O salads', 'Pastrami burgers'], farmersMarkets: 89, dietaryTrends: ['Unique LDS food culture influence', 'Lower alcohol consumption', 'Active outdoor lifestyle supporting lower obesity'] },
  { slug: 'vermont', name: 'Vermont', code: 'VT', obesityRate: 27.8, popularCuisines: ['Maple syrup', 'Cheddar cheese', 'Apple cider', 'Creemees (soft serve)'], farmersMarkets: 93, dietaryTrends: ['Highest per-capita organic farms', 'Strong farm-to-table ethos', 'High local and artisan food consumption'] },
  { slug: 'virginia', name: 'Virginia', code: 'VA', obesityRate: 31.0, popularCuisines: ['Virginia ham', 'Oysters', 'Peanut soup', 'Brunswick stew'], farmersMarkets: 278, dietaryTrends: ['Chesapeake Bay seafood heritage', 'Northern Virginia international diversity', 'Growing wine country food culture'] },
  { slug: 'washington', name: 'Washington', code: 'WA', obesityRate: 28.3, popularCuisines: ['Salmon', 'Geoduck', 'Rainier cherries', 'Aplets and Cotlets'], farmersMarkets: 312, dietaryTrends: ['High seafood and fresh produce consumption', 'Strong Pacific Rim cuisine influence', 'Leading organic and sustainable food movement'] },
  { slug: 'west-virginia', name: 'West Virginia', code: 'WV', obesityRate: 40.6, popularCuisines: ['Pepperoni rolls', 'Ramps', 'Tudor\'s biscuits', 'Maple syrup'], farmersMarkets: 97, dietaryTrends: ['Highest obesity rate tied with Arkansas', 'Appalachian food traditions', 'High food desert prevalence'] },
  { slug: 'wisconsin', name: 'Wisconsin', code: 'WI', obesityRate: 33.9, popularCuisines: ['Cheese curds', 'Bratwurst', 'Friday fish fry', 'Butter burgers', 'Kringle'], farmersMarkets: 278, dietaryTrends: ['Highest per-capita cheese consumption', 'Strong German food heritage', 'High dairy and beer consumption'] },
  { slug: 'wyoming', name: 'Wyoming', code: 'WY', obesityRate: 27.9, popularCuisines: ['Bison burgers', 'Elk steaks', 'Huckleberry everything', 'Trout'], farmersMarkets: 36, dietaryTrends: ['High game meat consumption', 'Ranch-style diets', 'Limited restaurant diversity in rural areas'] },
  { slug: 'district-of-columbia', name: 'District of Columbia', code: 'DC', obesityRate: 24.7, popularCuisines: ['Half-smoke sausages', 'Mumbo sauce', 'Ethiopian cuisine', 'Georgetown cupcakes'], farmersMarkets: 42, dietaryTrends: ['Highly diverse international food scene', 'Health-conscious urban population', 'Strong Ethiopian and West African food influence'] },
];

export function getAllStates(): StateData[] {
  return states;
}

export function getStateBySlug(slug: string): StateData | undefined {
  return states.find((s) => s.slug === slug);
}
